### PR TITLE
Create Bill.yml

### PR DESCRIPTION
**Pull request by pixelwake**
Following the GitHub basics class.

### CODE REVIEW

**Comment by wslack** [comment]
@rooneywp almost but not quite - the title of your file should match your Github username

**Comment by wslack** [comment]
Also, the emoji needs to be displayed like 'this' per the instructions

**Comment by pixelwake** [comment]
@wslack That's what I get for thinking I'm all pro :) Made the corrections.

**Comment by wslack** [comment]
Nicely done!

**Comment by wslack** [comment]
We had a bug in the site build, not caused by you. Will work to fix (in the meantime your addition won't appear yet).

**Comment by wslack** [comment]
Bug fixed, your name and emoji appears!

**Pull request merged**
