### PR TITLE
Create suprenant

### PR DESCRIPTION
**Pull request by suprenant**

### CODE REVIEW

**Comment by wslack** [comment]
Need to have .yml in your file title!

**Comment by suprenant** [comment]
@wslack oh! Got it, thanks. 

I just fixed that branch directly. Anything else, give a holler?

**Comment by wslack** [comment]
I think it also has to be titled with your GitHub username @suprenant

**Comment by suprenant** [comment]
@wslack fixed!

**Comment by wslack** [comment]
Done! You're on the main page. :dancer:

**Comment by suprenant** [comment]
Yahtzee! Thanks

**Pull request merged**
